### PR TITLE
Update libraries

### PR DESCRIPTION
**Pull request by bafain**

### CODE REVIEW

**Comment by fredefox** [comment]
I included all your changes here: https://github.com/fredefox/cat/commit/5684e99fda965dfb2d44dd120a5cfa67fc1b2d22

Git put me as a committer just because I rebased this on top of another change that came in. But it's the same diff.

Thanks a lot! I just installed Agda and tested it myself. It's really nice to see that it type checks with the newest versions of the dependencies!

**Comment by fredefox** [comment]
I also changed the "default branch" back to `master`. I don't know why I thought it would be nice to have another branch... You might need to update your remote tracking branches.

**Comment by bafain** [comment]
I don't know if you saw but they might be interested in parts of your development over at [cubical](https://github.com/agda/cubical/pull/215#issuecomment-579176478).

**Comment by fredefox** [comment]
Oh, that's cool. I didn't know about that. Thanks for letting me know!

**Pull request closed without merging**
