### PR TITLE
No need to clone dependencies to AGDA_DIR

### PR DESCRIPTION
**Pull request by bafain**

### CODE REVIEW

**Comment by fredefox** [comment]
The reason I didn't go with this is because now all Agda projects on the machine will be linked to whatever version is checked out in this repository, which is a bit odd. I really wish Agda had a way for projects to say give me this package with this exact version which you can download from this URL.

**Comment by bafain** [comment]
Unfortunately, [agda-pkg](https://github.com/agda/agda-pkg) does not seem to support installation of multiple versions of a library at the same time at the moment (f.i., `agda-pkg install standard-library==v1.3 cubical==v0.1` will _switch_ the installed versions of the two libraries to the specified ones and projects can only depend on the last installed versions of `standard-library` and `cubical` rather than `standard-library-1.3` and `cubical-0.1`), although there seems to be some support for that in the [library management](https://agda.readthedocs.io/en/latest/tools/package-system.html#version-numbers) system. By the way, `cat` is listed in the [package index](https://github.com/agda/package-index/tree/master/src/cat).

**Comment by fredefox** [comment]
That's cool. I didn't know that Agda had a package index. I was wishing for a better package management solution when I was working on it, looks like a few features have appeared there. I didn't know `agda-pkg` existed. Perhaps it would be a better idea to use that as part of the build process.

**Comment by bafain** [comment]
The issues with cloning the checked out submodules into a standard path seems to be 1) file duplication, 2) clash with other installed versions of the libraries and 3) missing instructions for when the dependency versions get bumped. Using `agda-pkg` could be a solution for the first and last issue but not the second at the moment it seems, and it has the additional issue that there does not seem to be a package for a version of `cubical` that works with the latest Agda release. If you still find it odd to globally register a library that is installed in a non-standard path even if it does not have the above issues, then there is also the possibility of declaring the source directories `libs/agda-stdlib/src` and `libs/cubical` as include paths in `cat.agda-lib`.

**Comment by fredefox** [comment]
I think I tried with using the include directive one time. I vaguely remember some other downside to it. I think maybe the issue was that if you already have declared those libraries in `$AGDA_DIR/libraries` then they will conflict.

It might be the best solution though. I'm undecided.

**Comment by bafain** [comment]
> I think I tried with using the include directive one time. I vaguely remember some other downside to it. I think maybe the issue was that if you already have declared those libraries in `$AGDA_DIR/libraries` then they will conflict.

There should not be an issue even if they are listed in `$AGDA_DIR/defaults` because the `.agda-lib` file takes precedence.

**Comment by fredefox** [comment]
> There should not be an issue even if they are listed in $AGDA_DIR/defaults because the .agda-lib file takes precedence.

Ah, that's great then! I think this is a change from last time I worked with it.

In any case I think it's better to get the "these two modules conflict" error than not using the right version of the dependencies and in stead getting various random type errors in stead.

If you feel that adding the modules to `include` is the best way, then I think we should just go with that for now. I really wish Agda had a package management solution similar to Haskell. I.e. a two-fold mechanism that lets package 1) stipulate dependency ranges and 2) a lock-file that says which exact versions to use to build a package.

**Comment by fredefox** [comment]
~dependency~ compatibility ranges*

**Pull request merged**
